## 예외

  - 정의

     - 프로그램이 실행 중에 예외 상황이나 오류가 발생했을 때 이를 처리하거나 전파하는 메커니즘을 의미합니다.
     
     - 프로그램이 예상치 못한 상황에 대처할 수 있도록 도와주며, 프로그램의 안정성을 높이는 역할을 합니다. 
     
     - 자바에서 예외처리는 try, catch, finally, throw, throws 등의 키워드와 예외 클래스 계층 구조를 기반으로 동작합니다.


  - 에러 (Error)와 예외(Exception)의 차이점
    
      -  에러는 코드 수정으로 해결가능한 심각한 수준의 문제이고,
      -  예외는 예외 처리 등 코드의 수정으로 처리가 가능한 상대적으로 심각하지 않은 수준의 문제이다.


     
-------------------------------------------------------------------------------------------------------------------------------

- 예외의 종류

 ![2019-03-02-java-checked-unchecked-exceptions-1](https://github.com/parkminseok56/Java/assets/133790403/2a3a9eb5-92d6-44a4-ae48-805f72e0c7dc)


 - 예외는 기본적으로 컴파일 중 예외와 런타임(실행 중) 에러, 논리적 에외가 존재함.

    그 중 런타임 에러는 Exception 조상 예외 객체를 상속받는 Checked 예외와, Exception 조상 객체의 자손인 RuntimeExpception 객체인 UnChecked 예외가 존재함. 
     
  - Checked 예외 (Checked Exception):
   
      - 컴파일러가 체크하며, **반드시 처리되어야 하는** 예외입니다.
    
      - 이 예외를 처리하지 않으면 컴파일 오류가 발생합니다.
    
      - 대표적으로  IOException이나 SQLException이 있습니다.

   - Unchecked 예외 (Unchecked Exception):
 
      - 컴파일러가 체크하지 않으며, 개발자의 경험과 주의로 예방하거나 처리해야 합니다.
    
      - 대표적으로 NullPointerException,  ArrayIndexOutOfBoundsException, ArithmeticException 등이 있습니다.

 -------------------------------------------------------------------------------------------------------------------------------

##  throw

  throw 문은 자바에서 예외를 프로그래머가 **의도적으로 발생시킬 때** 사용되는 구문입니다.
   
   이를 통해 프로그램의 특정 상황에서 예외를 강제로 발생시켜야 할 때 사용할 수 있습니다.
  
 - 사용하는 이유
  
   - 사용자 정의 예외 발생
   
     - 개발자가 직접 정의한 예외 클래스의 인스턴스를 생성하여 발생시킬 수 있습니다.
  
     - 이렇게 하면 프로그램에서 자신만의 예외를 정의하고 발생시킬 수 있어, 특정 상황에서 예외를 더 정확하게 표현할 수 있습니다.
  
   -  의미 있는 예외 발생
     
       - 특정 조건이 충족되지 않았을 때 예외를 발생시키면, 프로그램의 논리적 오류나 버그를 더 쉽게 발견할 수 있습니다.

-------------------------------------------------------------------------------------------------------------------------------

## try-catch

 try-Catch 문은 프로그래밍에서 예외 처리를 구현하는데 사용되는 구조입니다.
 
 예외(Exception)는 프로그램 실행 중에 예상치 못한 상황이 발생했을 때 발생하며, 이러한 예외를 처리하는 것은 프로그램의 안정성과 신뢰성을 높이는 데 도움이 됩니다.

다양한 상황에서 프로그램 실행 중에 오류나 예외 상황이 발생할 수 있습니다. 

이런 상황을 처리하기 위해 try-Catch 문은 코드 블록 내에 예외가 발생할 수 있는 코드를 넣고, 이 코드를 실행하는 동안 발생하는 예외를 캐치해서 처리할 수 있도록 도와줍니다.

아래는 Try-Catch 문의 기본적인 구조입니다:
 
``` java
try {
    // 예외가 발생할 수 있는 코드
} catch (예외의_종류1 예외_변수1) {
    // 예외1 처리 코드
} catch (예외의_종류2 예외_변수2) {
    // 예외2 처리 코드
} finally {
    // 항상 실행되는 코드 (선택 사항)
}

```

위의 구조에서 각각의 catch 블록은 특정 종류의 예외를 처리하는 데 사용됩니다. 

프로그램 실행 중에 해당하는 예외가 발생하면, 해당하는 catch 블록이 실행됩니다.

여러 종류의 예외를 처리하려면 여러 개의 catch 블록을 사용할 수 있습니다. 

만약 어떤 catch 블록도 해당되지 않는 예외가 발생한다면, 예외는 해당 try-catch 블록 외부로 전달됩니다.

또한, finally 블록은 선택 사항으로서 예외의 발생 여부와 관계없이 항상 실행되는 코드를 넣을 수 있습니다.

이 블록은 주로 리소스 해제나 정리 작업을 수행하는 데 사용됩니다.

-------------------------------------------------------------------------------------------------------------------------------
## try with resources

- "try with resources"는 자바(Java)에서 사용되는 중요한 기능 중 하나로, 자원 관리를 간단하고 효과적으로 처리하기 위한 기능입니다.
  
- 주로 입출력(IO) 스트림, 데이터베이스 연결 및 네트워크 연결과 같은 자원을 다룰 때 사용됩니다.
  
- 이를 통해 개발자는 자원을 명시적으로 해제하는 번거로움 없이 자원을 효과적으로 관리할 수 있습니다.

- "try with resources" 구문의 주요 특징과 동작 방식은 다음과 같습니다:

자원 선언: try-with-resources 구문을 사용하려면 다음과 같이 자원을 선언합니다.

```
try (자원의 선언) {
    // 자원을 사용하는 코드
} catch (예외 클래스 e) {
    // 예외 처리 코드
}
```

- 자원의 선언 부분에서는 자원을 초기화하는 코드를 작성합니다. 자원은 AutoCloseable 인터페이스를 구현하는 클래스의 인스턴스여야 합니다.

- 자원 해제: try 블록을 빠져나갈 때, 자원은 자동으로 해제됩니다. 이것은 자바 7 이후부터 제공되는 기능이며, 자원을 명시적으로 해제하거나 finally 블록을 사용할 필요가 없어집니다.

- 자원의 해제 순서: 자원은 선언된 역순으로 자동으로 해제됩니다. 즉, 가장 마지막에 선언된 자원이 가장 먼저 해제됩니다.
- 
```
try (FileInputStream fis = new FileInputStream("파일경로"), 
     FileOutputStream fos = new FileOutputStream("출력파일경로")) {
    // 파일 읽기 및 쓰기 작업 수행
} catch (IOException e) {
    // 예외 처리 코드
}
```

- 위의 예제에서 FileInputStream 및 FileOutputStream는 자원으로 선언되었으며, try 블록을 빠져나갈 때 자동으로 닫힙니다.
- 이렇게 하면 개발자가 명시적으로 자원을 닫는 코드를 작성하지 않아도 자원 누수를 방지할 수 있습니다.

- "try with resources" 구문을 사용하면 코드를 간결하게 유지하면서 자원 관리를 효과적으로 수행할 수 있으므로, 자바에서 자원 관리를 하는 데 매우 유용한 기능입니다.
